# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='balance.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rbalance.proto\x12\x03\x61pi\">\n\x1a\x41\x63\x63ountStatusReportRequest\x12\x0f\n\x07MsgType\x18# \x01(\t\x12\x0f\n\x07\x41\x63\x63ount\x18\x01 \x01(\x04\"p\n\x08Position\x12\x10\n\x08\x43urrency\x18\x0f \x01(\t\x12\r\n\x05\x41vgPx\x18\x06 \x01(\t\x12\x13\n\nPositionID\x18\xd2\x0c \x01(\x04\x12\x19\n\x10PositionOpenTime\x18\x8d\x0e \x01(\x03\x12\x13\n\nRealizedPL\x18\x8e\x0e \x01(\t\"\xc1\x01\n\x07\x42\x61lance\x12\x0f\n\x07\x41\x63\x63ount\x18\x01 \x01(\x04\x12\x10\n\x08\x43urrency\x18\x0f \x01(\t\x12\x17\n\x0eLastUpdateTime\x18\x8b\x06 \x01(\x03\x12\x12\n\tAvailable\x18\x89\x0e \x01(\t\x12\x0f\n\x06OnHold\x18\x8a\x0e \x01(\t\x12\x10\n\x07Settled\x18\x8b\x0e \x01(\t\x12\x0f\n\x06\x45quity\x18\xff\r \x01(\t\x12\x0f\n\x05\x42onus\x18\xd9\x98\x03 \x01(\t\x12!\n\tPositions\x18\x8c\x0e \x03(\x0b\x32\r.api.Position\"\x9c\x01\n\x19\x42\x61lanceIncrementalRefresh\x12\x0f\n\x07MsgType\x18# \x01(\t\x12\x0f\n\x07\x41\x63\x63ount\x18\x01 \x01(\x04\x12\x17\n\x0eLastUpdateTime\x18\x8b\x06 \x01(\x03\x12\x1f\n\x08\x42\x61lances\x18\x88\x0e \x03(\x0b\x32\x0c.api.Balance\x12\x15\n\x0cRejectReason\x18\xfc\x02 \x01(\t\x12\x0c\n\x04Text\x18: \x01(\tb\x06proto3')
)




_ACCOUNTSTATUSREPORTREQUEST = _descriptor.Descriptor(
  name='AccountStatusReportRequest',
  full_name='api.AccountStatusReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='api.AccountStatusReportRequest.MsgType', index=0,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Account', full_name='api.AccountStatusReportRequest.Account', index=1,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=84,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='api.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Currency', full_name='api.Position.Currency', index=0,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AvgPx', full_name='api.Position.AvgPx', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PositionID', full_name='api.Position.PositionID', index=2,
      number=1618, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PositionOpenTime', full_name='api.Position.PositionOpenTime', index=3,
      number=1805, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RealizedPL', full_name='api.Position.RealizedPL', index=4,
      number=1806, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=198,
)


_BALANCE = _descriptor.Descriptor(
  name='Balance',
  full_name='api.Balance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Account', full_name='api.Balance.Account', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Currency', full_name='api.Balance.Currency', index=1,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LastUpdateTime', full_name='api.Balance.LastUpdateTime', index=2,
      number=779, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Available', full_name='api.Balance.Available', index=3,
      number=1801, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OnHold', full_name='api.Balance.OnHold', index=4,
      number=1802, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Settled', full_name='api.Balance.Settled', index=5,
      number=1803, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Equity', full_name='api.Balance.Equity', index=6,
      number=1791, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Bonus', full_name='api.Balance.Bonus', index=7,
      number=52313, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Positions', full_name='api.Balance.Positions', index=8,
      number=1804, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=394,
)


_BALANCEINCREMENTALREFRESH = _descriptor.Descriptor(
  name='BalanceIncrementalRefresh',
  full_name='api.BalanceIncrementalRefresh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='api.BalanceIncrementalRefresh.MsgType', index=0,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Account', full_name='api.BalanceIncrementalRefresh.Account', index=1,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LastUpdateTime', full_name='api.BalanceIncrementalRefresh.LastUpdateTime', index=2,
      number=779, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Balances', full_name='api.BalanceIncrementalRefresh.Balances', index=3,
      number=1800, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RejectReason', full_name='api.BalanceIncrementalRefresh.RejectReason', index=4,
      number=380, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Text', full_name='api.BalanceIncrementalRefresh.Text', index=5,
      number=58, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=553,
)

_BALANCE.fields_by_name['Positions'].message_type = _POSITION
_BALANCEINCREMENTALREFRESH.fields_by_name['Balances'].message_type = _BALANCE
DESCRIPTOR.message_types_by_name['AccountStatusReportRequest'] = _ACCOUNTSTATUSREPORTREQUEST
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Balance'] = _BALANCE
DESCRIPTOR.message_types_by_name['BalanceIncrementalRefresh'] = _BALANCEINCREMENTALREFRESH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountStatusReportRequest = _reflection.GeneratedProtocolMessageType('AccountStatusReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTSTATUSREPORTREQUEST,
  __module__ = 'balance_pb2'
  # @@protoc_insertion_point(class_scope:api.AccountStatusReportRequest)
  ))
_sym_db.RegisterMessage(AccountStatusReportRequest)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'balance_pb2'
  # @@protoc_insertion_point(class_scope:api.Position)
  ))
_sym_db.RegisterMessage(Position)

Balance = _reflection.GeneratedProtocolMessageType('Balance', (_message.Message,), dict(
  DESCRIPTOR = _BALANCE,
  __module__ = 'balance_pb2'
  # @@protoc_insertion_point(class_scope:api.Balance)
  ))
_sym_db.RegisterMessage(Balance)

BalanceIncrementalRefresh = _reflection.GeneratedProtocolMessageType('BalanceIncrementalRefresh', (_message.Message,), dict(
  DESCRIPTOR = _BALANCEINCREMENTALREFRESH,
  __module__ = 'balance_pb2'
  # @@protoc_insertion_point(class_scope:api.BalanceIncrementalRefresh)
  ))
_sym_db.RegisterMessage(BalanceIncrementalRefresh)


# @@protoc_insertion_point(module_scope)
