# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: margin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='margin.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmargin.proto\x12\x03\x61pi\"Q\n\x0cMarginAmount\x12\x12\n\tMarginAmt\x18\xed\x0c \x01(\t\x12\x16\n\rMarginAmtType\x18\xec\x0c \x01(\t\x12\x15\n\x0cMarginAmtCcy\x18\xee\x0c \x01(\t\"\xa8\x01\n\x17MarginRequirementReport\x12\x0f\n\x07MsgType\x18# \x01(\t\x12\x1b\n\x12MarginReqmtRptType\x18\xc7\x0e \x01(\t\x12\x0f\n\x07\x41\x63\x63ount\x18\x01 \x01(\x04\x12)\n\rMarginAmounts\x18\xeb\x0c \x03(\x0b\x32\x11.api.MarginAmount\x12\x15\n\x0cRejectReason\x18\xfc\x02 \x01(\t\x12\x0c\n\x04Text\x18: \x01(\tb\x06proto3')
)




_MARGINAMOUNT = _descriptor.Descriptor(
  name='MarginAmount',
  full_name='api.MarginAmount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MarginAmt', full_name='api.MarginAmount.MarginAmt', index=0,
      number=1645, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MarginAmtType', full_name='api.MarginAmount.MarginAmtType', index=1,
      number=1644, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MarginAmtCcy', full_name='api.MarginAmount.MarginAmtCcy', index=2,
      number=1646, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=102,
)


_MARGINREQUIREMENTREPORT = _descriptor.Descriptor(
  name='MarginRequirementReport',
  full_name='api.MarginRequirementReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='api.MarginRequirementReport.MsgType', index=0,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MarginReqmtRptType', full_name='api.MarginRequirementReport.MarginReqmtRptType', index=1,
      number=1863, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Account', full_name='api.MarginRequirementReport.Account', index=2,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MarginAmounts', full_name='api.MarginRequirementReport.MarginAmounts', index=3,
      number=1643, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RejectReason', full_name='api.MarginRequirementReport.RejectReason', index=4,
      number=380, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Text', full_name='api.MarginRequirementReport.Text', index=5,
      number=58, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=273,
)

_MARGINREQUIREMENTREPORT.fields_by_name['MarginAmounts'].message_type = _MARGINAMOUNT
DESCRIPTOR.message_types_by_name['MarginAmount'] = _MARGINAMOUNT
DESCRIPTOR.message_types_by_name['MarginRequirementReport'] = _MARGINREQUIREMENTREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarginAmount = _reflection.GeneratedProtocolMessageType('MarginAmount', (_message.Message,), dict(
  DESCRIPTOR = _MARGINAMOUNT,
  __module__ = 'margin_pb2'
  # @@protoc_insertion_point(class_scope:api.MarginAmount)
  ))
_sym_db.RegisterMessage(MarginAmount)

MarginRequirementReport = _reflection.GeneratedProtocolMessageType('MarginRequirementReport', (_message.Message,), dict(
  DESCRIPTOR = _MARGINREQUIREMENTREPORT,
  __module__ = 'margin_pb2'
  # @@protoc_insertion_point(class_scope:api.MarginRequirementReport)
  ))
_sym_db.RegisterMessage(MarginRequirementReport)


# @@protoc_insertion_point(module_scope)
